name: nyati
description: A CLI tool to create Flutter projects with a custom folder structure.
version: 1.0.5
repository: https://github.com/IsayaOsward/nyati-flutter.git
documentation: https://github.com/IsayaOsward/nyati-flutter#readme

executables:
  nyati: nyati


environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  path: ^1.9.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

